# Generated by Django 5.1.7 on 2025-03-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='example_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='method_images/', verbose_name='Изображение кода'),
        ),
    ]
