# Generated by Django 5.1.7 on 2025-03-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_method_example_code_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='description',
        ),
        migrations.RemoveField(
            model_name='method',
            name='example_code_image',
        ),
        migrations.AlterField(
            model_name='method',
            name='name',
            field=models.CharField(max_length=95, verbose_name='Название метода'),
        ),
    ]
