# Generated by Django 5.1.7 on 2025-03-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000, verbose_name='Главный2 текст')),
                ('description', models.TextField(max_length=10000, verbose_name='Длинный2 текст')),
            ],
        ),
    ]
