# Generated by Django 5.1.7 on 2025-03-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
