# Generated by Django 5.1.7 on 2025-03-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Загаловок метода')),
                ('name', models.CharField(max_length=95, verbose_name='Название метода')),
            ],
        ),
    ]
