# Generated by Django 5.1.7 on 2025-03-28 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Names',
        ),
    ]
