# Generated by Django 5.1.7 on 2025-03-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_names'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Names',
        ),
        migrations.AddField(
            model_name='method',
            name='description',
            field=models.TextField(default='', verbose_name='Описание метода'),
        ),
        migrations.AddField(
            model_name='method',
            name='example_code_image',
            field=models.ImageField(default='', upload_to='code_images/', verbose_name='Изображение примера кода'),
        ),
    ]
